version: "3.9"

services:
    cassandra-node1:
        image: cassandra:4.0
        container_name: cs-node1
        ports:
            - "9042:9042"
        volumes:
            - ./cassandra-configs-node1:/etc/cassandra/N
            - ./cassandra-data-node1:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=cassandra-test
            - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
            - CASSANDRA_NUM_TOKENS=128
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_RACK=rack1
            - CASSANDRA_DC=dc1
        networks:
            - cassandra_network

    cassandra-node2:
        image: cassandra:4.0
        container_name: cs-node2
        ports:
            - "9043:9042"
        volumes:
            - ./cassandra-configs-node2:/etc/cassandra/N
            - ./cassandra-data-node2:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTER_NAME=cassandra-test
            - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
            - CASSANDRA_NUM_TOKENS=128
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_RACK=rack2
            - CASSANDRA_DC=dc2
        networks:
            - cassandra_network

networks:
    cassandra_network:
        driver: bridge
